### ISSUE TITLE
[BUG] Not functioning

### ISSUE THREAD

**Issue by peytonw96** [qbcore-framework/qb-pawnshop#10]
Script loads fine, upon going to the blip, there is no interaction with the door, nor is there an interior portion of the building, tried adjusting the vectors, no dice.

**Comment by peytonw96** [comment]
also, time of day has been checked, well within working hours, and normal business days, tried monday through friday 07-1700 (checked every hour)

**Comment by yamieboi** [comment]
> also, time of day has been checked, well within working hours, and normal business days, tried monday through friday 07-1700 (checked every hour)

Are you getting any errors? cause the code is fine and i fixed a bug yesterday and found no problems with the menu not showing up..

**Comment by peytonw96** [comment]
No errors, I will try removing the current qb-pawnshop and replacing it
later today.

**Comment by yamieboi** [comment]
okay...

**Comment by peytonw96** [comment]
pawnshop shows up now, however, crashes when i try to sell anything

**Comment by Demo4889** [comment]
I just test this with the updated version, and everything is working perfectly fine for me @peytonw96

**Comment by peytonw96** [comment]
> I just test this with the updated version, and everything is working perfectly fine for me @peytonw96

updated QB-Input and it fixed my issue, and i had to use the updated pawnshop script. @Demo4889
