### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ozziYT** [qbcore-framework/qb-pawnshop#11]
when player set -1 they get what they have in inventory they selling it then -1 they get it back az much they want
sory for my english

**Comment by djkenada** [comment]
What he is saying is, anything you sell using a negative number, instead of selling the item, it gives you that ammount.
Sell -1 get +1
Sell -10 get +10
Doesn't seem to give or take money.

**Comment by Demo4889** [comment]
I'll be working on this fix, and another fix regarding the melting of items tonight

**Comment by Demo4889** [comment]
This will be fixed with PR #12
