### ISSUE TITLE
pawnshop menu

### ISSUE THREAD

**Issue by Berk0S** [qbcore-framework/qb-pawnshop#20]
when i sell something the menu closes i have to go back 5 6 steps then come back again then go back and come to open the menu again to sell something cant you make it when you sell something to open automaticly after every sell like the vehicleshop

**Comment by Demo4889** [comment]
I'll work on it. Thank you for the suggestion.

**Comment by BerkieBb** [comment]
> I'll work on it. Thank you for the suggestion.

Are you still working on it?

**Comment by Demo4889** [comment]
> > I'll work on it. Thank you for the suggestion.
> 
> Are you still working on it?

I was working on this, but I have since been removed from the QBCore team without being notified as to why.

**Comment by GhzGarage** [comment]
Moved this to a new issue, thanks for the suggestion. The dev team will work on this
