### ISSUE TITLE
[SUGGESTION] Adding more locations?

### ISSUE THREAD

**Issue by twigmasters** [qbcore-framework/qb-pawnshop#44]
I just updated and decided to try adding a new location in the south side of the city but when I go there I am not getting a menu. Am I missing something? This is how I edited the config.lua below.

Config.PawnLocation = {
    [1] = {
            coords = vector3(412.34, 314.81, 103.13),
            length = 1.5,
            width = 1.8,
            heading = 207.0,
            debugPoly = false,
            minZ = 100.97,
            maxZ = 105.42,
            distance = 3.0
        },
    [2] = {
            coords = vector3(183.33, -1320.07, 29.32),
            length = 1.5,
            width = 1.8,
            heading = 59.42,
            debugPoly = false,
            minZ = 100.97,
            maxZ = 105.42,
            distance = 3.0
        },
    }

**Comment by KamuiKody** [comment]
for entry #2 your minz needs to be below the z in your coords and the maxz should be above it.

**Comment by xHTGxReaperx** [comment]
anyone know what im doing wrong with this Config = {}

Config.PawnLocation = {
    [1] = {
        coords = vector3(412.34, 314.81, 103.13),
        length = 1.5,
        width = 1.8,
        heading = 207.0,
        debugPoly = false,
        minZ = 100.97,
        maxZ = 105.42,
        distance = 3.0
    },
    [2] = {
        coords = vector3(1197.26, -3254.16, 7.1),
        length = 1.5,
        width = 1.8,
        heading = 96.09,
        debugPoly = false,
        minZ = minZ, -- Replace minZ with the minimum Z coordinate of the interaction area
        maxZ = maxZ, -- Replace maxZ with the maximum Z coordinate of the interaction area
        distance = 3.0
    },
}

Config.PawnItems = {
    [1] = { -- For Pawn Location 1
        { item = 'goldchain', price = math.random(50, 100) },
        { item = 'diamond_ring', price = math.random(50, 100) },
        { item = 'rolex', price = math.random(50, 100) },
        { item = '10kgoldchain', price = math.random(50, 100) },
    },
    [2] = { -- For Pawn Location 2
        { item = 'markedbills', price = math.random(50, 100) },
        { item = 'moneybag', price = math.random(50, 100) }
    }
}

Config.BankMoney = false -- Set to true if you want the money to go into the player's bank
Config.UseTimes = false -- Set to false if you want the pawnshop open 24/7
Config.TimeOpen = 7 -- Opening Time
Config.TimeClosed = 17 -- Closing Time
Config.SendMeltingEmail = true

Config.UseTarget = GetConvar('UseTarget', 'false') == 'true'

Config.MeltingItems = { -- meltTime is the amount of time in minutes per item
    [1] = {
        item = 'goldchain',
        rewards = {
            [1] = {
                item = 'goldbar',
                amount = 2
            }
        },
        meltTime = 0.15
    },
    [2] = {
        item = 'diamond_ring',
        rewards = {
            [1] = {
                item = 'diamond',
                amount = 1
            },
            [2] = {
                item = 'goldbar',
                amount = 1
            }
        },
        meltTime = 0.15
    },
    [3] = {
        item = 'rolex',
        rewards = {
            [1] = {
                item = 'diamond',
                amount = 1
            },
            [2] = {
                item = 'goldbar',
                amount = 1
            },
            [3] = {
                item = 'electronickit',
                amount = 1
            }
        },
        meltTime = 0.15
    },
    [4] = {
        item = '10kgoldchain',
        rewards = {
            [1] = {
                item = 'diamond',
                amount = 5
            },
            [2] = {
                item = 'goldbar',
                amount = 1
            }
        },
        meltTime = 0.15
    },
}
